# This is a basic workflow to help you get started with Actions

name: MATRIX Automation

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v4

      # check state of phone
      # install webdriver app
      # install cafe app
        

      # check status
      #   curl http://10.11.1.1:8100/status

      
      - name: install appium tools
        run: npm i -g appium

        
      - name: install xcuitest
        run: appium driver install xcuitest


      - name: run appium
        run: appium&


      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed


      - name: install python tools
        run: |
          pip install -r requirements.txt
          # pip install -U pymobiledevice3 && brew install libusb
          # pymobiledevice3 mounter auto-mount


      # - name: mount device
      #   run: pymobiledevice3 mounter auto-mount


      - name: open and foward port 8100
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: python -c 'from main import setPortForwarding; setPortForwarding()'


      - name: Download Cafe ipa
        run: curl -L -o Corellium_Cafe.ipa https://www.corellium.com/hubfs/Corellium_Cafe.ipa


      - name: Install Cafe app on VM
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: python -c 'from main import installApp; installApp("Corellium_Cafe.ipa")'


      # - name: Download Webdriver ipa
      #   run: curl -L -o WebDriverAgentRunner-Runner.ipa https://www.corellium.com/hubfs/Blog%20Attachments/WebDriverAgentRunner-Runner.ipa


      # - name: Install Webdriver app on VM
      #   env:
      #     API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
      #   run: python -c 'from main import installApp; installApp("WebDriverAgentRunner-Runner.ipa")'


      - name: Run Webdriver app on VM
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: python -c 'from main import runApp; runApp("org.appium.WebDriverAgentRunner.xctrunner")'


      - name: Create Matrix Assessment
        id: create_test
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: |
          assessment_id=$(python -c 'from main import createMatrixAssessment; createMatrixAssessment("com.corellium.Cafe")')
          echo "assessment_id=$assessment_id" >> $GITHUB_OUTPUT


      - name: echo assessment id
        run: echo "${{ steps.create_test.outputs.assessment_id }}"


      # - name: test connection
      #   run: curl http://10.11.1.4

      - name: Start Matrix monitoring
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: python -c 'from main import startMatrixMonitoring; startMatrixMonitoring("${{ steps.create_test.outputs.assessment_id }}")'


      - name: Stop Matrix monitoring
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: python -c 'from main import stopMatrixMonitoring; stopMatrixMonitoring("${{ steps.create_test.outputs.assessment_id }}")'


      - name: Execute Matrix test
        env:
          API_KEY: ${{ secrets.CORELLIUM_TOKEN }}
        run: python -c 'from main import executeMatrixTests; executeMatrixTests("${{ steps.create_test.outputs.assessment_id }}")'
      
      

